#pragma once

#include "..\..\pch.h"


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Classes
//---------------------------------------------------------------------------

// AnimBlueprintGeneratedClass SAW_3P_AnimBP_V3.SAW_3P_AnimBP_V3_C
// 0x8978 (FullSize[0x8E98] - InheritedSize[0x0520])
class USAW_3P_AnimBP_V3_C : public UPortalWarsAnimInstanceV2
{
public:
	struct FPointerToUberGraphFrame                    UberGraphFrame;                                            // 0x0520(0x0008) (ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                              AnimGraphNode_Root;                                        // 0x0528(0x0030)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_14;                           // 0x0558(0x0158)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_31;                      // 0x06B0(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_30;                      // 0x07A0(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_29;                      // 0x0890(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_28;                      // 0x0980(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_27;                      // 0x0A70(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_26;                      // 0x0B60(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_25;                      // 0x0C50(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_24;                      // 0x0D40(0x00F0)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_14;                        // 0x0E30(0x0050)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_23;                      // 0x0E80(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_22;                      // 0x0F70(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_21;                      // 0x1060(0x00F0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_13;                           // 0x1150(0x0158)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_32;                            // 0x12A8(0x0028)
	struct FAnimNode_MakeDynamicAdditive               AnimGraphNode_MakeDynamicAdditive_6;                       // 0x12D0(0x0038)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_20;                      // 0x1308(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_19;                      // 0x13F8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_18;                      // 0x14E8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_17;                      // 0x15D8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_16;                      // 0x16C8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_15;                      // 0x17B8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_14;                      // 0x18A8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_13;                      // 0x1998(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_12;                      // 0x1A88(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_11;                      // 0x1B78(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_10;                      // 0x1C68(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_9;                       // 0x1D58(0x00F0)
	struct FAnimNode_MakeDynamicAdditive               AnimGraphNode_MakeDynamicAdditive_5;                       // 0x1E48(0x0038)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_12;                           // 0x1E80(0x0158)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_8;                       // 0x1FD8(0x00F0)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_7;                       // 0x20C8(0x00F0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_31;                            // 0x21B8(0x0028)
	struct FAnimNode_MakeDynamicAdditive               AnimGraphNode_MakeDynamicAdditive_4;                       // 0x21E0(0x0038)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_6;                       // 0x2218(0x00F0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_30;                            // 0x2308(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_11;                           // 0x2330(0x0158)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_10;                           // 0x2488(0x0158)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_18;                         // 0x25E0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_17;                         // 0x2608(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_16;                         // 0x2630(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_15;                         // 0x2658(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_14;                         // 0x2680(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_13;                         // 0x26A8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_12;                         // 0x26D0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_11;                         // 0x26F8(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_17;                           // 0x2720(0x0080)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_9;                               // 0x27A0(0x00C8)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_16;                           // 0x2868(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_26;                              // 0x28E8(0x0058)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_10;                              // 0x2940(0x0030)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_10;                         // 0x2970(0x0028)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_15;                           // 0x2998(0x0080)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_8;                               // 0x2A18(0x00C8)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_14;                           // 0x2AE0(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_25;                              // 0x2B60(0x0058)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_9;                               // 0x2BB8(0x0030)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_24;                              // 0x2BE8(0x0058)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_5;                       // 0x2C40(0x00F0)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_8;                               // 0x2D30(0x0030)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_23;                              // 0x2D60(0x0058)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_13;                           // 0x2DB8(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_22;                              // 0x2E38(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_21;                              // 0x2E90(0x0058)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_12;                           // 0x2EE8(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_20;                              // 0x2F68(0x0058)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_4;                           // 0x2FC0(0x00B0)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_19;                              // 0x3070(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_18;                              // 0x30C8(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_17;                              // 0x3120(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_16;                              // 0x3178(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_15;                              // 0x31D0(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_14;                              // 0x3228(0x0058)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_11;                           // 0x3280(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_13;                              // 0x3300(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_12;                              // 0x3358(0x0058)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_10;                           // 0x33B0(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_11;                              // 0x3430(0x0058)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_12;                         // 0x3488(0x00C0)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_10;                              // 0x3548(0x0058)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_6;                          // 0x35A0(0x00E8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_5;                          // 0x3688(0x00E8)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_13;                        // 0x3770(0x0050)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_12;                        // 0x37C0(0x0050)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_9;                            // 0x3810(0x0080)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_11;                         // 0x3890(0x00C0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_10;                         // 0x3950(0x00C0)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_9;                               // 0x3A10(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_8;                               // 0x3A68(0x0058)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_5;                           // 0x3AC0(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_8;                            // 0x3B60(0x0080)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_7;                               // 0x3BE0(0x00C8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_4;                          // 0x3CA8(0x00E8)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_7;                               // 0x3D90(0x0058)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_7;                               // 0x3DE8(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_3;                              // 0x3E18(0x00B0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_9;                          // 0x3EC8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_8;                          // 0x3EF0(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_7;                          // 0x3F18(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_6;                          // 0x3F40(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_5;                          // 0x3F68(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_4;                          // 0x3F90(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_3;                          // 0x3FB8(0x0028)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive_2;                             // 0x3FE0(0x00C8)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_11;                        // 0x40A8(0x0050)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_6;                               // 0x40F8(0x0058)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_4;                           // 0x4150(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_7;                            // 0x41F0(0x0080)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_29;                            // 0x4270(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_6;                               // 0x4298(0x0030)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_10;                        // 0x42C8(0x0050)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_6;                            // 0x4318(0x0080)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_5;                            // 0x4398(0x0080)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_5;                               // 0x4418(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_4;                               // 0x4470(0x0058)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_6;                               // 0x44C8(0x00C8)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_4;                            // 0x4590(0x0080)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_3;                           // 0x4610(0x00A0)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_5;                               // 0x46B0(0x00C8)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_5;                               // 0x4778(0x0030)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_3;                               // 0x47A8(0x0058)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_3;                            // 0x4800(0x0080)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_4;                               // 0x4880(0x0030)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_28;                            // 0x48B0(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_3;                               // 0x48D8(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine_2;                              // 0x4908(0x00B0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_9;                            // 0x49B8(0x0158)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_4;                       // 0x4B10(0x00F0)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_3;                     // 0x4C00(0x0020)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_11;                               // 0x4C20(0x0108)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_3;                     // 0x4D28(0x0020)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_3;                       // 0x4D48(0x00F0)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool_2;                           // 0x4E38(0x00A0)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer_2;                            // 0x4ED8(0x0080)
	struct FAnimNode_LinkedAnimGraph                   AnimGraphNode_SubInstance;                                 // 0x4F58(0x00A0)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult_2;                          // 0x4FF8(0x0028)
	struct FAnimNode_TransitionResult                  AnimGraphNode_TransitionResult;                            // 0x5020(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_27;                            // 0x5048(0x0028)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult_2;                               // 0x5070(0x0030)
	struct FAnimNode_SequencePlayer                    AnimGraphNode_SequencePlayer;                              // 0x50A0(0x0080)
	struct FAnimNode_StateResult                       AnimGraphNode_StateResult;                                 // 0x5120(0x0030)
	struct FAnimNode_StateMachine                      AnimGraphNode_StateMachine;                                // 0x5150(0x00B0)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_10;                               // 0x5200(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_9;                                // 0x5308(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_8;                                // 0x5410(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_7;                                // 0x5518(0x0108)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_8;                            // 0x5620(0x0158)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_6;                                // 0x5778(0x0108)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace_2;                     // 0x5880(0x0020)
	struct FAnimNode_RotateRootBone                    AnimGraphNode_RotateRootBone;                              // 0x58A0(0x00A0)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_9;                         // 0x5940(0x0050)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_5;                                // 0x5990(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_4;                                // 0x5A98(0x0108)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_3;                                // 0x5BA0(0x0108)
	struct FAnimNode_ConvertLocalToComponentSpace      AnimGraphNode_LocalToComponentSpace;                       // 0x5CA8(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace_2;                     // 0x5CC8(0x0020)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone_2;                                // 0x5CE8(0x0108)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_26;                            // 0x5DF0(0x0028)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator_2;                       // 0x5E18(0x00F0)
	struct FAnimNode_ModifyBone                        AnimGraphNode_ModifyBone;                                  // 0x5F08(0x0108)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_8;                    // 0x6010(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_25;                            // 0x60E0(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_24;                            // 0x6108(0x0028)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_4;                               // 0x6130(0x00C8)
	unsigned char                                      UnknownData_37XC[0x8];                                     // 0x61F8(0x0008) MISSED OFFSET (FIX SPACE BETWEEN PREVIOUS PROPERTY)
	struct FAnimNode_TwoBoneIK                         AnimGraphNode_TwoBoneIK_2;                                 // 0x6200(0x01E0)
	struct FAnimNode_TwoBoneIK                         AnimGraphNode_TwoBoneIK;                                   // 0x63E0(0x01E0)
	struct FAnimNode_ConvertComponentToLocalSpace      AnimGraphNode_ComponentToLocalSpace;                       // 0x65C0(0x0020)
	struct FAnimNode_BlendSpaceEvaluator               AnimGraphNode_BlendSpaceEvaluator;                         // 0x65E0(0x00F0)
	struct FAnimNode_HandIKRetargeting                 AnimGraphNode_HandIKRetargeting;                           // 0x66D0(0x0120)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_3;                          // 0x67F0(0x00E8)
	struct FAnimNode_MakeDynamicAdditive               AnimGraphNode_MakeDynamicAdditive_3;                       // 0x68D8(0x0038)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_7;                            // 0x6910(0x0158)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_3;                           // 0x6A68(0x00B0)
	struct FAnimNode_MakeDynamicAdditive               AnimGraphNode_MakeDynamicAdditive_2;                       // 0x6B18(0x0038)
	struct FAnimNode_BlendListByBool                   AnimGraphNode_BlendListByBool;                             // 0x6B50(0x00A0)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer_2;                          // 0x6BF0(0x00E8)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_3;                               // 0x6CD8(0x00C8)
	struct FAnimNode_BlendSpacePlayer                  AnimGraphNode_BlendSpacePlayer;                            // 0x6DA0(0x00E8)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_8;                         // 0x6E88(0x0050)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_7;                         // 0x6ED8(0x0050)
	struct FAnimNode_ApplyAdditive                     AnimGraphNode_ApplyAdditive;                               // 0x6F28(0x00C8)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_9;                          // 0x6FF0(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_23;                            // 0x70B0(0x0028)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_7;                    // 0x70D8(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_22;                            // 0x71A8(0x0028)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum_2;                           // 0x71D0(0x00B0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_8;                          // 0x7280(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_21;                            // 0x7340(0x0028)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_6;                    // 0x7368(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_20;                            // 0x7438(0x0028)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_5;                    // 0x7460(0x00D0)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_6;                            // 0x7530(0x0158)
	struct FAnimNode_MakeDynamicAdditive               AnimGraphNode_MakeDynamicAdditive;                         // 0x7688(0x0038)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_19;                            // 0x76C0(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_5;                            // 0x76E8(0x0158)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_7;                          // 0x7840(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_18;                            // 0x7900(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_17;                            // 0x7928(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_16;                            // 0x7950(0x0028)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_4;                    // 0x7978(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_15;                            // 0x7A48(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_6;                          // 0x7A70(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_14;                            // 0x7B30(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_13;                            // 0x7B58(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_5;                          // 0x7B80(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_12;                            // 0x7C40(0x0028)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_3;                    // 0x7C68(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_11;                            // 0x7D38(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_3;                                      // 0x7D60(0x0048)
	struct FAnimNode_BlendListByEnum                   AnimGraphNode_BlendListByEnum;                             // 0x7DA8(0x00B0)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive_2;                    // 0x7E58(0x00D0)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_4;                          // 0x7F28(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_10;                            // 0x7FE8(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_4;                            // 0x8010(0x0158)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend_2;                               // 0x8168(0x00C8)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_9;                             // 0x8230(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_3;                          // 0x8258(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_8;                             // 0x8318(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_3;                            // 0x8340(0x0158)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_7;                             // 0x8498(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_6;                             // 0x84C0(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_5;                             // 0x84E8(0x0028)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend_2;                          // 0x8510(0x00C0)
	struct FAnimNode_ApplyMeshSpaceAdditive            AnimGraphNode_ApplyMeshSpaceAdditive;                      // 0x85D0(0x00D0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_4;                             // 0x86A0(0x0028)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_3;                             // 0x86C8(0x0028)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose_2;                            // 0x86F0(0x0158)
	struct FAnimNode_SaveCachedPose                    AnimGraphNode_SaveCachedPose;                              // 0x8848(0x0158)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose_2;                             // 0x89A0(0x0028)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve_2;                               // 0x89C8(0x0058)
	struct FAnimNode_ModifyCurve                       AnimGraphNode_ModifyCurve;                                 // 0x8A20(0x0058)
	struct FAnimNode_LayeredBoneBlend                  AnimGraphNode_LayeredBoneBlend;                            // 0x8A78(0x00C0)
	struct FAnimNode_UseCachedPose                     AnimGraphNode_UseCachedPose;                               // 0x8B38(0x0028)
	struct FAnimNode_Slot                              AnimGraphNode_Slot_2;                                      // 0x8B60(0x0048)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_6;                         // 0x8BA8(0x0050)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_5;                         // 0x8BF8(0x0050)
	struct FAnimNode_TwoWayBlend                       AnimGraphNode_TwoWayBlend;                                 // 0x8C48(0x00C8)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_4;                         // 0x8D10(0x0050)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_3;                         // 0x8D60(0x0050)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator_2;                         // 0x8DB0(0x0050)
	struct FAnimNode_Slot                              AnimGraphNode_Slot;                                        // 0x8E00(0x0048)
	struct FAnimNode_SequenceEvaluator                 AnimGraphNode_SequenceEvaluator;                           // 0x8E48(0x0050)


	static UClass* StaticClass()
	{
		static auto ptr = UObject::FindClass("AnimBlueprintGeneratedClass SAW_3P_AnimBP_V3.SAW_3P_AnimBP_V3_C");
		return ptr;
	}



	void AnimGraph(struct FPoseLink* AnimGraph);
	void ExecuteUbergraph_SAW_3P_AnimBP_V3(int EntryPoint);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
